name = "LoadFlint"
uuid = "472f376f-f1cf-461b-9ac1-d103423be9b7"
authors = ["Claus Fieker <fieker@mathematik.uni-kl.de>"]
version = "0.1.3"

[deps]
BinaryProvider = "b99e7846-7c00-51b0-8f62-c81ae34c0232"
GMP_jll = "781609d7-10c4-51f6-84f2-b8444358ff6d"
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"
flint_jll = "cabf4574-4f87-5802-9a0b-e4b5b01a80fc"

[compat]
BinaryProvider = "0.4, 0.5"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
